name: Deploy Next.js to DigitalOcean

on:
  push:
    branches:
      - main  # Change if your main branch is named differently
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519  # Using your private key
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

    - name: Start SSH Agent and Add Key
      run: |
        eval $(ssh-agent -s)  # Start ssh-agent
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -  # Add the private key to the agent

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no user@${{ secrets.DROPLET_IP }} \
          "cd /var/www/audioscriba && git pull && npm install && npm run build && pm2 restart audioscriba"
