name: Deploy Next.js app to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up SSH key and passphrase
      - name: Set up SSH for deployment
        run: |
          # Create the SSH directory if it doesn't exist
          mkdir -p ~/.ssh

          # Store the private SSH key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

          # Set permissions for the private key (secure it)
          chmod 600 ~/.ssh/id_rsa

          # Add Droplet's SSH key to the known_hosts file
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

          # Set up the SSH agent and add the SSH key with passphrase
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")

      # Step 3: Deploy your app
      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} "cd /var/www/audioscriba && git pull && npm install && npm run build && pm2 restart app"
